apiVersion: v1
kind: Service
metadata:
  name: demo-svc
spec:
  selector:
    app: demo-svc 
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-svc-deployment
  labels:
    app: demo-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-svc
  template:
    metadata:
      labels:
        app: demo-svc
    spec:
      containers:
      - name: demo-svc
        image: gcr.io/kubernetes-demo-212517/demo-svc:latest
        ports:
        - containerPort: 8080